@startuml

package Models {
        class Location

        abstract class User {
                string Username
                int Score
        }
        class Client {
                PaymentCard PaymentCard
                List<Ride> Rides
        }
        class Driver {
                Location CurrentLocation
        }
        class PaymentCard {
            string CardData
        }
        
        enum PaymentType{
                Cash
                PaymentCard
        }
        enum RideStatus {
                Looking
                Waiting
                InProgress
                Complete
                Cancelled
        }
        enum RideType {
                Economy,
                Business,
                Ultra,
        }
        class Ride {
                Client Client
                Driver Driver
                Location StartLocation
                List<Location> TargetLocations
                decimal Cost
                RideStatus RideStatus
                RideType RideType
                int ClientScore
                int DriverScore
        }

        Client --|> User
        Driver --|> User

        Driver o-- Location

        Ride o-- Client
        Ride o-- Driver
        Ride o-- Location
        Ride *-- RideStatus
        Ride *-- RideType
        Ride *-- PaymentType
        Client *-- PaymentCard
}

class Repos
Repos --> Client
Repos --> Driver
Repos --> Ride


package Server {
        interface IVuberController
        interface IHubContext
        class VuberController
        VuberController --|> IVuberController
        VuberController --> Repos
        VuberController --> IHubContext

        abstract class VuberHub
        class ClientHub{
                OrderRide(Location startLocation, Location targetLocation, RideType rideType)
                AddPaymentCard(string CardData)
                SeeRides()
                ScoreDriver()
        }
        class DriverHub
        ClientHub --|> VuberHub
        DriverHub --|> VuberHub
        ClientHub --> IVuberController
        DriverHub --> IVuberController

        class UserIdProvider
        UserIdProvider --> VuberController
        VuberHub --> UserIdProvider

        interface IVuberClient
        interface IClientClient
        interface IDriverClient
        IClientClient --|> IVuberClient
        IDriverClient --|> IVuberClient
        ClientHub --> IClientClient
        DriverHub --> IDriverClient
}

@enduml
